runtime: docker: Update base version for clang-android to debian13
Building -next with clang-android reveals it is using a version of
openssl that does not support CMS_NO_SIGNING_TIME:

  scripts/sign-file.c:282:4: error: use of undeclared identifier 'CMS_NO_SIGNING_TIME'
    282 |                         CMS_NO_SIGNING_TIME |
        |                         ^~~~~~~~~~~~~~~~~~~

This is a simple bug in the kernel that is being addressed [1] but for
the same reason that the majority of toolchain containers were bumped to
Debian 13 in commit 46280e2 ("runtime: Migrate toolchains from Debian 12
to Debian 13 base containers"), update clang-android's base image to
Debian 13 to avoid future issues such as this.

Link: https://lore.kernel.org/SN6PR02MB415708C0A6E2EB1B5C7BBFB0D49CA@SN6PR02MB4157.namprd02.prod.outlook.com/ [1]
Signed-off-by: Nathan Chancellor <nathan@kernel.org>